/**
 * Vendor a subset of Maki into the source tree.
 *
 * Maki is CC0 — public domain, no attribution obligation — which is the whole
 * reason it is the set this library can use. Anything under MIT or ISC (Tabler,
 * Lucide, however good they look) would propagate a credit-line requirement into
 * every map anyone generates, and a library that quietly does that to its users
 * is not one worth shipping.
 *
 * The art is inlined at build time and committed, rather than regenerated on
 * every install, so a checkout builds identically without the icon package
 * present. Re-run this when the subset changes:
 *
 *     npm run build:icons
 *
 * Maki has 215 icons and covers what sits on the ground. It has no `oil`,
 * `natural-gas`, `pipeline` or `mine` — the geopolitical half a news map runs
 * on does not exist in any public-domain set and has to be drawn. That is a
 * separate piece of work and this file is deliberately not it.
 */
import { readFile, writeFile } from "node:fs/promises";

const SOURCE = "node_modules/@mapbox/maki/icons";
const OUT = "src/icons.ts";

/**
 * The subset, grouped by what a map is usually saying when it reaches for one.
 * Kept small on purpose: a vocabulary nobody can hold in their head is one
 * where every author picks a different icon for the same thing.
 */
const CHOSEN = {
  "movement and logistics": ["airport", "harbor", "rail", "ferry", "bus", "fuel", "bridge"],
  "industry and energy": ["industry", "warehouse", "dam", "windmill", "construction"],
  "civic and public": [
    "hospital",
    "police",
    "fire-station",
    "school",
    "bank",
    "embassy",
    "town-hall",
  ],
  settlement: ["town", "city", "village"],
  "land and landmark": ["mountain", "park", "lighthouse", "monument"],
  situation: ["danger", "roadblock", "shelter"],
};

/**
 * Undo XML character references.
 *
 * Several of Maki's files carry their line breaks inside the `d` attribute as
 * `&#xA;` and `&#x9;` rather than as literal whitespace. Captured raw and
 * emitted straight back out, the `&` is escaped on the way into the document
 * and the path arrives containing the seven literal characters `&#xA;` — which
 * is not a path command, and the icon draws as nothing.
 */
function decode(text) {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number(dec)))
    .replace(/&amp;/g, "&");
}

/** The `d` of the path (or paths) Maki draws each icon with. */
function pathOf(svg, name) {
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]*)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`${name}: no path`);
  // Whitespace inside a `d` is legal, and Maki's files carry tabs and newlines
  // from hand-editing. Collapsing it keeps the emitted module readable and the
  // output byte-stable.
  const cleaned = paths.map((d) => decode(d).replace(/\s+/g, " ").trim());
  for (const d of cleaned) {
    if (/[&<>"]/.test(d)) throw new Error(`${name}: path still carries markup: ${d.slice(0, 60)}`);
    if (!/^[MmZzLlHhVvCcSsQqTtAa0-9eE,.\s+-]+$/.test(d)) {
      throw new Error(`${name}: path has a character no path command uses`);
    }
  }
  return cleaned.join(" ");
}

const entries = [];
for (const [group, names] of Object.entries(CHOSEN)) {
  const icons = [];
  for (const name of names) {
    const svg = await readFile(`${SOURCE}/${name}.svg`, "utf8");
    const box = /viewBox="([^"]*)"/.exec(svg)?.[1];
    if (box !== "0 0 15 15") throw new Error(`${name}: unexpected viewBox ${box}`);
    icons.push({ name, d: pathOf(svg, name) });
  }
  entries.push({ group, icons });
}

const body = entries
  .map(
    ({ group, icons }) =>
      `  // ${group}\n` +
      icons.map((i) => `  ${JSON.stringify(i.name)}: ${JSON.stringify(i.d)},`).join("\n"),
  )
  .join("\n");

const total = entries.reduce((n, e) => n + e.icons.length, 0);

await writeFile(
  OUT,
  `/**
 * Maki, inlined.
 *
 * Generated by \`scripts/build-icons.mjs\` from \`@mapbox/maki\` — do not edit by
 * hand. Maki is CC0, which is the reason it is the set this library uses: a set
 * requiring attribution would propagate that obligation into every map anyone
 * generates. Every icon is drawn on the same 15x15 grid at the same weight, so
 * two of them side by side look like one set rather than two.
 *
 * The paths are inlined per mark rather than referenced from a \`<symbol>\`.
 * A \`<use>\` puts its content in a shadow tree, where a class-based fill is
 * unreliable across renderers and unreachable by the flattening pass — and the
 * flattened form exists precisely for the reader that ignores stylesheets. This
 * project has shipped that failure three times; duplicating a few hundred bytes
 * of path data is much the cheaper mistake.
 *
 * ${total} icons. Maki has 215 and covers what sits on the ground; it has no
 * \`oil\`, \`natural-gas\`, \`pipeline\` or \`mine\`, so the geopolitical half a news
 * map runs on still has to be drawn.
 */

/** Every icon is drawn on this grid, in its own units. */
export const ICON_GRID = 15;

export const ICONS: Readonly<Record<string, string>> = Object.freeze({
${body}
});

export const ICON_NAMES: readonly string[] = Object.freeze(Object.keys(ICONS));

export function isIconName(value: string): boolean {
  return Object.hasOwn(ICONS, value);
}
`,
  "utf8",
);

console.log(`  ${OUT}  ${total} icons from Maki (CC0)`);
